
CREATE TYPE USER_TYPE AS ENUM ('ADMIN', 'LEAD', 'STUDENT');

CREATE TABLE PROFILE (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE,
    ROLE USER_TYPE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE CLUB (
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    CATEGORY TEXT NOT NULL,
    LEADID INT REFERENCES PROFILE(ID),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);


CREATE TABLE CLUB_MEMBER (
    ID SERIAL PRIMARY KEY,
    CLUB_ID INT NOT NULL REFERENCES CLUB(ID),
    MEMBER_ID INT NOT NULL REFERENCES PROFILE(ID),
    JOINED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (CLUB_ID, MEMBER_ID)
);


CREATE TABLE EVENT (
    ID SERIAL PRIMARY KEY,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    DATE TIMESTAMP NOT NULL,
    LOCATION TEXT NOT NULL,
    CLUB_ID INT NOT NULL REFERENCES CLUB(ID),
    REGIISTRATION_LIMIT INT NOT NULL,
    REGISTRATION_COUNT INT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE EVENT_REGISTRATION (
    ID SERIAL PRIMARY KEY,
    EVENT_ID INT NOT NULL REFERENCES EVENT(ID),
    MEMBER_ID INT NOT NULL REFERENCES PROFILE(ID),
    REGISTERED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    attended BOOLEAN DEFAULT FALSE,
    UNIQUE (EVENT_ID, MEMBER_ID)
);

CREATE TABLE ANNOUNCEMENT (
    ID SERIAL PRIMARY KEY,
    TITLE TEXT NOT NULL,
    CONTENT TEXT NOT NULL,
    CLUB_ID INT NOT NULL REFERENCES CLUB(ID),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);